-- =====================================================
-- ACTUALIZACIÓN: Tablas faltantes de seguimiento
-- =====================================================

CREATE TABLE IF NOT EXISTS TB_SEGUIMIENTO_RECOMENDACIONES (
    ID_SEGUIMIENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_RECOMENDACION INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    REALIZADA TINYINT(1) DEFAULT 0,
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_RECOMENDACION) REFERENCES TB_RECOMENDACIONES(ID_RECOMENDACION) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TB_SEGUIMIENTO_EMOCIONAL_ACTIVIDAD (
    ID_SEGUIMIENTO_ACTIVIDAD INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_RECOMENDACION INT NOT NULL,
    ID_EMOCION INT NOT NULL,
    NIVEL_INTENSIDAD INT DEFAULT 5,
    OBSERVACION TEXT,
    REALIZADA TINYINT(1) DEFAULT 0,
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_RECOMENDACION) REFERENCES TB_RECOMENDACIONES(ID_RECOMENDACION) ON DELETE CASCADE,
    FOREIGN KEY (ID_EMOCION) REFERENCES TB_EMOCIONES(ID_EMOCION) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_seguimiento_usuario ON TB_SEGUIMIENTO_RECOMENDACIONES(ID_USUARIO);
